"use client";
import Link from "@/components/mindcompass/page-link";
import { useEffect, useState } from "react";
import { api, type Attempt } from "@/lib/client";
import { scales } from "@/lib/assessment/registry";
export function Catalogue(){const [attempts,setAttempts]=useState<Attempt[]>([]),[allowed,setAllowed]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{api<{consented:boolean}>("session").then(async s=>{setAllowed(s.consented);if(s.consented)setAttempts((await api<{attempts:Attempt[]}>("attempts")).attempts);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 // Fail closed while loading or when consent cannot be verified, including direct URLs.
 if(loading)return <section className="panel"><h1>参与确认</h1><p role="status">正在读取参与状态…</p></section>;
 if(!allowed||error)return <section className="panel"><h1>开始之前，请先确认参与说明</h1><p>请在首页勾选成年确认和知情同意，再点击“开始测量”。</p>{error&&<p role="alert">{error}</p>}<Link className="button primary" href="/#consent">前往参与说明</Link></section>;
 return <><div className="page-heading"><p className="eyebrow">探索，从一个问题开始</p><h1>今天，你想了解哪一面？</h1><p>每份问卷独立保存。你可以随时退出、随时回来，继续未完成的探索。</p></div>{loading?<p role="status">正在读取参与状态…</p>:!allowed?<div className="notice"><p>开始前，请先阅读并同意参与说明。</p><Link className="button primary" href="/#consent">前往参与说明</Link></div>:null}{error&&<p role="alert">{error}</p>}
 {(["personality","attitudes"] as const).map((category,index)=><section className="catalogue-section" key={category}><div className="section-heading"><span className="section-index">0{index+1}</span><div><h2>{category==="personality"?"人格特质":"态度或行为倾向"}</h2><p>{category==="personality"?"观察相对稳定的偏好，也为变化留出空间。":"从具体情境出发，理解自己的选择。"}</p></div></div><div className="assessment-grid">{scales.filter(s=>s.category===category).map((s,i)=>{const draft=attempts.find(a=>a.scaleId===s.id&&a.status==="draft"),done=attempts.find(a=>a.scaleId===s.id&&a.status==="completed");return <article className={`assessment-card tone-${index*3+i}`} key={s.id}><div className="card-top"><span className="card-icon" aria-hidden="true">{["✧","♡","△","⌘","↗","◎"][index*3+i]}</span><span className="badge">{s.exploratory?"探索性问卷":"有来源的研究量表"}</span></div><h3>{s.name}</h3><p>{s.purpose}</p><div className="card-meta"><span>{s.items.length} 题</span><span>约 {s.minutes} 分钟</span><span>{s.options.length} 级作答</span></div>{s.id==="love-attitudes"&&<p className="card-caveat">LAS-42原题许可待核实；当前为六取向原创探索问卷。</p>}{s.id==="tripm"&&<p className="card-caveat">公开原版＋中文辅助译文；中文尚未验证。</p>}{draft&&<p className="saved-label">已保存 {Object.keys(draft.answers).length} / {s.items.length} 题</p>}<Link className="card-action" href={allowed?`/assessments/${s.id}${draft?`?attempt=${draft.id}`:""}`:"/#consent"}>{draft?"继续作答":"开始探索"}<span aria-hidden="true">→</span></Link>{done&&<Link className="result-link" href={`/results/${done.id}`}>查看上次结果</Link>}</article>;})}</div></section>)}
 {attempts.some(a=>a.status==="completed")&&<section className="panel"><h2>本浏览器的已完成记录</h2><ul className="history-list">{attempts.filter(a=>a.status==="completed").map(a=><li key={a.id}><Link href={`/results/${a.id}`}>{scales.find(s=>s.id===a.scaleId)?.name||"旧版28题探索问卷"}<span>{new Date(a.completedAt!).toLocaleDateString("zh-CN")}</span></Link></li>)}</ul></section>}</>;
}
