/* eslint-disable @next/next/no-location-assign-relative-destination -- vinext beta soft-navigation recovery regression; saved state is restored from D1. */
"use client";
import { useState } from "react";
import Link from "@/components/mindcompass/page-link";
import { api } from "@/lib/client";
import { CONSENT_VERSION } from "@/lib/policy";
export function Home(){const [agreed,setAgreed]=useState(false),[adult,setAdult]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function start(){setBusy(true);setError("");try{await api("session","POST",{accepted:agreed,adult,consentVersion:CONSENT_VERSION});window.location.assign("/assessments");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><section className="hero"><div><p className="eyebrow">认识自己，不急着定义自己</p><h1>给内心的探索，<br/>一个温柔的方向。</h1><p className="hero-copy">从人格特质到日常选择，通过一份份问卷，观察你的感受、态度与行为倾向。让好奇成为起点，让理解留有空间。</p><div className="hero-tags"><span>自愿参与</span><span>随机匿名编号</span><span>教育与研究</span></div><a className="text-link" href="#consent">阅读参与说明，开始探索 <span aria-hidden="true">↗</span></a></div><div className="compass-art" aria-hidden="true"><div className="compass-ring ring-one"/><div className="compass-ring ring-two"/><span className="compass-n">N</span><span className="compass-e">E</span><span className="compass-s">S</span><span className="compass-w">W</span><div className="compass-needle"/><span className="art-label">每个方向，都有值得认识的你</span><span className="art-dot"/></div></section>
 <section className="intro-grid" aria-label="探索内容"><article><span className="card-number">01 / 人格特质</span><h2>可视化自己的相处方式</h2><p>通过大五人格、爱情态度与三元人格特质，提供观察自己与他人关系的不同视角。</p></article><article><span className="card-number">02 / 态度与行为</span><h2>理解日常选择的倾向</h2><p>探索对人工智能的态度、面对不确定性的选择，以及团队协作中的习惯。</p></article></section>
 <section id="consent" className="consent-card"><div><p className="eyebrow">开始之前，请花一点时间</p><h2>你的参与，由你决定。</h2><p>本平台仅面向已满18岁的参与者，用于人格、态度和行为倾向的教育／研究性自我探索。</p></div><div className="consent-details"><h3>我们会收集什么？</h3><p>通过逐题回答、完全匿名、随机参与者编号，获得同意状态、量表版本、维度得分、开始与完成时间和完成状态。全过程不要求告知姓名、手机号、邮箱等个人隐私。</p><h3>如何使用与保留？</h3><p>数据用于汇总分析、课程／研究作业展示和改善问卷体验。未完成答案将作为草稿保存，7天后过期；已完成数据最多保留180天。关闭页面或返回选题页后，可在同一浏览器继续。</p><h3>随时退出</h3><p>你可随时离开，也可主动清除本次草稿。隐私页提供撤回并删除本浏览器全部参与数据的操作。清除浏览器Cookie后，我们无法凭姓名找回你的记录。</p><div className="boundary-note">请悉知：本测评不构成临床、医学或心理诊断，也不能替代专业意见。结果不用于治疗、人员筛选或其他高风险决策。</div><Link href="/privacy" className="text-link">查看完整隐私说明</Link><span className="link-separator">·</span><Link href="/feedback" className="text-link">联系与反馈</Link>
 <label className="check-row"><input type="checkbox" checked={adult} onChange={e=>setAdult(e.target.checked)}/>我确认已满18岁</label><label className="check-row"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)}/>我已阅读并同意上述参与说明及隐私说明</label><button className="button primary consent-start" disabled={!agreed||!adult||busy} onClick={start}>{busy?"正在记录同意…":"开始测量"}<span aria-hidden="true">→</span></button>{error&&<p role="alert" className="error-message">{error}</p>}<p className="fine-print">同意说明版本：{CONSENT_VERSION}。页面展示不含未经证实的用户数量或评价。</p></div></section></>;
}
