"use client";
import { useState } from "react";
import Link from "@/components/mindcompass/page-link";
import { api } from "@/lib/client";
import { CONSENT_VERSION } from "@/lib/policy";
export function Privacy({contactEmail}:{contactEmail?:string}){const [confirm,setConfirm]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function withdraw(){setBusy(true);try{await api("session","DELETE");setMessage("已撤回参与并删除当前浏览器会话对应的答卷、同意记录和反馈分类。你可重新阅读说明后参与。");setConfirm(false);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <article className="prose-page"><p className="eyebrow">参与与隐私 · {CONSENT_VERSION}</p><h1>把选择权留在你手里。</h1><section><h2>目的与适用对象</h2><p>面向18岁及以上参与者，用于非商业教育与研究性自我探索。本站结果不构成任何临床、医学或心理诊断，也不能替代专业意见。</p>{contactEmail&&<p>有关研究目的、参与者权利或数据处理的问题，可联系研究负责人：<a href={`mailto:${contactEmail}`}>{contactEmail}</a>。</p>}</section><section><h2>最少必要的数据</h2><p>保存随机参与者编号、同意版本与时间、是否确认成年、所选量表版本、逐题选项、维度得分、开始及完成时间与完成状态。反馈入口只收集问题分类。我们不要求姓名、手机号、邮箱、学号、精确地址或设备指纹，不使用广告或行为追踪工具。</p><p>浏览器通过必要的HttpOnly会话Cookie关联同一参与者。编号和Cookie属于可关联的随机标识，而非可证明的完全不可识别数据；数据库仅保存会话令牌哈希。管理员的登录身份不写入参与者答卷。</p></section><section><h2>保存、退出与删除</h2><p>已保存草稿在同一浏览器可恢复，最后一次保存后7天过期。点“退出并清除本次草稿”会立即清除本次答案，保留不含答案的退出状态用于完成率统计。完成答卷最多保留180天；会话最长180天，从首次同意起计算，因此部分后续答卷可能随会话更早删除。</p><p>应用每次访问都会处理过期数据；每日清理任务还会在无人访问时执行。研究者后台显示最近一次定时清理的真实运行记录。过期内容不进入读取或分析。备份、托管访问日志与已导出文件另由研究负责人按同等保留原则管理。</p><p>你可使用下方操作撤回并删除本浏览器全部参与数据。删除后无法恢复。清除Cookie或换设备后，本站无法通过姓名或联系方式定位原记录；知道结果网址或参与者编号也不能读取或删除他人记录。</p></section><section><h2>数据用途与访问</h2><p>数据仅用于汇总分析、课程／研究作业展示及问卷体验改进。只有通过管理密码登录的研究者能查看汇总与导出。公众无法浏览参与者数据。导出仅含必要的随机编号、量表版本、选项、得分、日期和耗时，不包含会话凭据或管理员身份。</p><p>站点托管于 Cloudflare Workers，数据存储于 Cloudflare D1。应用代码不保存IP和User-Agent；托管平台为网络传输和运行维护可能处理访问日志，日志策略与数据存储地域须由研究负责人核实。请勿向反馈中加入身份信息。</p></section><section><h2>研究边界</h2><p>探索性问卷尚未完成信效度验证。BFI-2使用已公开的中文版研究来源；TriPM中文辅助译文未经独立回译；爱情态度探索题不是LAS-42原题或标准译本。这里没有人群常模、诊断阈值或“超过多少人”的比较。</p></section><section className="notice"><h2>撤回本浏览器的参与</h2>{confirm?<><p>这会删除当前参与编号下所有量表的答案和结果、同意记录与反馈分类，无法恢复。是否继续？</p><button className="button danger" onClick={withdraw} disabled={busy}>确认撤回并删除全部参与数据</button><button className="button secondary" onClick={()=>setConfirm(false)}>取消</button></>:<button className="button secondary" onClick={()=>setConfirm(true)}>撤回并删除我的参与数据</button>}{message&&<p role="status">{message}</p>}</section><p><Link href="/feedback">联系与反馈</Link> · <Link href="/">返回首页</Link></p></article>;
}
