import { generalLimit, type Scale } from "./types";
// Original English items and key: PhenX PX121601 (freely available, no permission required).
// Chinese glosses are project translations, not a validated Chinese TriPM.
const rows: [string,string][] = [
 ["I’m optimistic more often than not.","大多数时候，我是乐观的。"],
 ["How other people feel is important to me.","他人的感受对我很重要。"],
 ["I often act on immediate needs.","我常常按眼前的需要采取行动。"],
 ["I have no strong desire to parachute out of an airplane.","我没有很强的从飞机上跳伞的愿望。"],
 ["I’ve often missed things I promised to attend.","我常常没有参加自己答应要出席的事情。"],
 ["I would enjoy being in a high-speed chase.","我会享受高速追逐的体验。"],
 ["I am well-equipped to deal with stress.","我很有能力应对压力。"],
 ["I don’t mind if someone I dislike gets hurt.","如果我不喜欢的人受到伤害，我并不介意。"],
 ["My impulsive decisions have caused problems with loved ones.","我的冲动决定曾给我与亲近之人的关系带来问题。"],
 ["I get scared easily.","我很容易感到害怕。"],
 ["I sympathize with others’ problems.","我对他人遇到的困难抱有同情。"],
 ["I have missed work without bothering to call in.","我曾缺勤，却没有打电话告知。"],
 ["I’m a born leader.","我天生适合做领导者。"],
 ["I enjoy a good physical fight.","我喜欢痛快地打上一架。"],
 ["I jump into things without thinking.","我会不经思考就着手做事。"],
 ["I have a hard time making things turn out the way I want.","我很难让事情按自己的愿望发展。"],
 ["I return insults.","别人侮辱我时，我会回骂。"],
 ["I’ve gotten in trouble because I missed too much school.","我曾因为缺课太多而惹上麻烦。"],
 ["I have a knack for influencing people.","我擅长影响他人。"],
 ["It doesn’t bother me to see someone else in pain.","看到别人痛苦并不会让我感到不安。"],
 ["I have good control over myself.","我有良好的自我控制能力。"],
 ["I function well in new situations, even when unprepared.","即使没有准备，我在新情境中也能应对自如。"],
 ["I enjoy pushing people around sometimes.","有时我喜欢摆布别人。"],
 ["I have taken money from someone’s purse or wallet without asking.","我曾未经允许从别人的钱包里拿钱。"],
 ["I don’t think of myself as talented.","我不认为自己有才能。"],
 ["I taunt people just to stir things up.","我会为了挑起事端而嘲弄别人。"],
 ["People often abuse my trust.","别人常常辜负我的信任。"],
 ["I’m afraid of far fewer things than most people.","与大多数人相比，让我害怕的事情少得多。"],
 ["I don’t see any point in worrying if what I do hurts someone else.","我觉得没有必要担心自己的行为是否会伤害别人。"],
 ["I keep appointments I make.","我会遵守自己约好的安排。"],
 ["I often get bored quickly and lose interest.","我常常很快就感到无聊并失去兴趣。"],
 ["I can get over things that would traumatize others.","一些会让别人受到严重打击的事情，我能够从中恢复。"],
 ["I am sensitive to the feelings of others.","我对别人的感受很敏感。"],
 ["I have conned people to get money from them.","我曾欺骗别人以获取他们的钱。"],
 ["It worries me to go into an unfamiliar situation without knowing all the details.","在不知道全部细节的情况下进入陌生情境，会让我担心。"],
 ["I don’t have much sympathy for people.","我对别人没有太多同情。"],
 ["I get in trouble for not considering the consequences of my actions.","我会因为不考虑行为后果而惹上麻烦。"],
 ["I can convince people to do what I want.","我能说服别人按我的意愿行事。"],
 ["For me, honesty really is the best policy.","对我而言，诚实确实是最好的处事方式。"],
 ["I’ve injured people to see them in pain.","我曾为了看到别人痛苦而伤害他们。"],
 ["I don’t like to take the lead in groups.","我不喜欢在群体中带头。"],
 ["I sometimes insult people on purpose to get a reaction from them.","我有时会故意侮辱别人，以引起他们的反应。"],
 ["I have taken items from a store without paying for them.","我曾从商店拿走物品而没有付款。"],
 ["It’s easy to embarrass me.","我很容易感到难堪。"],
 ["Things are more fun if a little danger is involved.","带一点危险的事情会更有趣。"],
 ["I have a hard time waiting patiently for things I want.","对于自己想要的东西，我很难耐心等待。"],
 ["I stay away from physical danger as much as I can.","我会尽可能避开人身危险。"],
 ["I don’t care much if what I do hurts others.","我不太在意自己的行为是否伤害别人。"],
 ["I have lost a friend because of irresponsible things I’ve done.","我曾因自己不负责任的行为而失去朋友。"],
 ["I don’t stack up well against most others.","与大多数人相比，我觉得自己不够出色。"],
 ["Others have told me they are concerned about my lack of self-control.","别人曾告诉我，他们担心我缺乏自我控制。"],
 ["It’s easy for me to relate to other people’s emotions.","我很容易体会到别人的情绪。"],
 ["I have robbed someone.","我曾抢劫过别人。"],
 ["I never worry about making a fool of myself with others.","我从不担心在别人面前出丑。"],
 ["It doesn’t bother me when people around me are hurting.","周围的人在受苦时，我并不会因此感到不安。"],
 ["I have had problems at work because I was irresponsible.","我曾因为不负责任而在工作中遇到问题。"],
 ["I’m not very good at influencing people.","我不太擅长影响别人。"],
 ["I have stolen something out of a vehicle.","我曾从车辆里偷过东西。"],
];
const boldness = [1,4,7,10,13,16,19,22,25,28,32,35,38,41,44,47,50,54,57];
const meanness = [2,6,8,11,14,17,20,23,26,29,33,36,39,40,42,45,48,52,55];
const reverse = [2,4,10,11,16,21,25,30,33,35,39,41,44,47,50,52,57];
export const tripm: Scale = {
 id:"tripm",version:"original-en-zh-gloss-2026-09-12",versionDate:"2026-09-12",name:"三元人格特质 TriPM",category:"personality",language:"en + zh-CN project translation",exploratory:true,
 purpose:"以公开原版的三维结构，探索大胆性、人际关切与行为抑制相关倾向。",minutes:"10–15",
 instructions:"本项目保留公开原版58题、四级选项与0–3计分。中文为项目辅助译文，未经回译验证；英文原题同步显示。请选择最符合自己的描述，没有对错。题目涉及不愉快或违规经历，不愿回答时可退出并清除草稿。",
 limitations:generalLimit+"英文题目和评分键取自公开原版；中文辅助译文尚未经过独立双语回译和中文样本验证，所以本次中文使用仅属探索性。维度及总和不是风险等级，也不能据此判断任何人是否属于某类人格。",
 source:{id:"phenx-tripm",citation:"Patrick (2010), Triarchic Psychopathy Measure; PhenX PX121601.",url:"https://phenxtoolkit.org/protocols/view/121601?origin=domain",permission:"PhenX 标注 freely available; permission not required for use。",adaptation:"英文原题、题号、反向键及0–3计分保留；中文为项目辅助译文，未经独立回译验证，不冒称标准中文版。"},
 options:[{value:3,label:"符合（True）"},{value:2,label:"比较符合（Somewhat true）"},{value:1,label:"比较不符合（Somewhat false）"},{value:0,label:"不符合（False）"}],
 scoring:{min:0,max:3,aggregation:"sum",total:"sum",missing:"reject",thresholds:null},
 dimensions:[{id:"boldness",name:"大胆性",description:"描述社交自信、压力下的镇定和对不确定情境的接受倾向。"},{id:"meanness",name:"冷酷倾向",description:"描述题目中对他人感受较少关切、较疏离或对抗的自报倾向。这是维度名称，不是对你的道德或人格定性。"},{id:"disinhibition",name:"去抑制",description:"描述冲动、计划不足或行为控制困难的自报倾向，不能据此预测违规或作临床判断。"}],
 items:rows.map(([originalText,text],i)=>({id:`TP${i+1}`,text,originalText,dimensionId:boldness.includes(i+1)?"boldness":meanness.includes(i+1)?"meanness":"disinhibition",reverse:reverse.includes(i+1),sourceId:"phenx-tripm"})),
};
